import os
import sys

def setup_environment():
    print("==================================================")
    print("        Vigilance.ai - Environment Setup          ")
    print("==================================================")
    
    backend_dir = os.path.dirname(os.path.abspath(__file__))
    env_path = os.path.join(backend_dir, ".env")
    example_path = os.path.join(backend_dir, ".env.example")
    
    if os.path.exists(env_path):
        overwrite = input(".env file already exists. Overwrite? (y/N): ").strip().lower()
        if overwrite != 'y':
            print("Setup cancelled. Existing .env preserved.")
            return

    # Load defaults from .env.example
    defaults = {}
    if os.path.exists(example_path):
        with open(example_path, "r") as f:
            for line in f:
                if "=" in line and not line.strip().startswith("#"):
                    k, v = line.strip().split("=", 1)
                    defaults[k] = v
    
    # Prompt user for keys
    print("\nPlease provide the API keys. Press Enter to use simulated fallbacks (ideal for demo/offline).")
    
    gemini_key = input(f"Enter GEMINI_API_KEY [{defaults.get('GEMINI_API_KEY', '')}]: ").strip()
    vt_key = input(f"Enter VIRUSTOTAL_API_KEY [{defaults.get('VIRUSTOTAL_API_KEY', '')}]: ").strip()
    nvd_key = input(f"Enter NVD_API_KEY [{defaults.get('NVD_API_KEY', '')}]: ").strip()
    
    gemini_key = gemini_key or defaults.get('GEMINI_API_KEY', 'your_gemini_api_key_here')
    vt_key = vt_key or defaults.get('VIRUSTOTAL_API_KEY', 'your_virustotal_api_key_here')
    nvd_key = nvd_key or defaults.get('NVD_API_KEY', 'your_nvd_api_key_here')
    
    # Write to .env
    with open(env_path, "w") as f:
        f.write("# Generated by setup_env.py\n")
        f.write(f"GEMINI_API_KEY={gemini_key}\n")
        f.write(f"VIRUSTOTAL_API_KEY={vt_key}\n")
        f.write(f"NVD_API_KEY={nvd_key}\n")
        f.write("CHROMA_DB_PATH=./chromadb_data\n")
        f.write("PORT=8000\n")
        f.write("HOST=0.0.0.0\n")
        
    print(f"\nSuccessfully generated {env_path}")
    print("Ready to start the backend layer.")
    print("==================================================")

if __name__ == "__main__":
    setup_environment()
